spring:
  application:
    name: BLOCK BACKEND

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    #    url: jdbc:postgresql://192.168.2.100:5432/pract
    url: jdbc:postgresql://192.168.2.100:5432/pract?currentSchema=blog
    username: postgres
    password: 123
    driverClassName: org.postgresql.Driver


