server:
  port: 8899

spring:

  web:
    resources:
      static-locations: classpath:file:./webapps/
  mvc:
    static-path-pattern: /**


  application:
    name: mmblog

datasource:
  url: jdbc:h2:mem:mydb
  username: sa
  password: password
  driverClassName: org.h2.Driver


