spring.application.name=mmblog
database=POSTGRESQL 
jpa.hibernate.ddl-auto=update
driver.name=org.postgresql.Driver
#    url: jdbc:postgresql://192.168.2.100:5432/pract
datasource.url=jdbc:postgresql://192.168.2.100:5432/pract?currentSchema=blog
datasource.username=postgres
datasource.password=123
datasource.driverClassName=org.postgresql.Driver
servlet.multipart.enabled=true
